{{- if and .Values.job.enabled .Values.huggingface.token (not .Values.huggingface.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unlimited-ocr.jobName" . }}-hf
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  HF_TOKEN: {{ .Values.huggingface.token | quote }}
{{- end }}
